### ISSUE TITLE
Flux is unable to discover the network adapters on Kali 2.0

### ISSUE THREAD

**Issue by strasharo** [deltaxflux/flux#2]
I'm trying to use flux on Kali 2.0 (the system I'm using usually linset on) and it's unable to find the two wireless adapters attached to it:

`root@kalif:/home/kali/flux# ./
s Not a Social Enginering Tool             #
 #                                                       #
 #########################################################

Aircrack-ng.....OK!
Aireplay-ng.....OK!
Airmon-ng.......OK!
Airodump-ng.....OK!
Awk.............OK!
Curl............OK!
Dhcpd...........OK!
Hostapd.........OK!
Iwconfig........OK!
Lighttpd........OK!
Macchanger......OK!
Mdk3............OK!
Nmap............OK!
Php5-cgi........OK!
Pyrit...........OK!
Python..........OK!
Unzip...........OK!
et..........OK!
.ge:www.flux.jimdo.de 
                              s Not a Social Enginering Tool             #
 #                                                       #
 #########################################################

**Autodetect Resolution ...
1024x768

There are no wireless cards, quit...

[ ] Cleaning and closing
[-] Cleaning iptables
[-] Restoring tput
[-] Delete files
[-] Restarting NetworkManager
[ +]  Cleaning performed successfully!
root@kalif:/home/kali/flux# **
`

Here are the adapters attached to the VM:

`root@kalif:/home/kali# iwconfig 
alfa1     IEEE 802.11bg  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=33 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
eth0      no wireless extensions.

alfa2     IEEE 802.11bgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=33 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
lo        no wireless extensions.

root@kalif:/home/kali# airmon-ng 

PHY	Interface	Driver		Chipset

phy0	alfa1		rtl8187		Realtek Semiconductor Corp. RTL8187
phy1	alfa2		ath9k_htc	Atheros Communications, Inc. AR9271 802.11n

root@kalif:/home/kali# 
`

**Comment by deltaxflux** [comment]
I now this bug,  I hope I can fix it soon.  Flux is working on Linux Mint / Ubuntu
I think you should change mon0 to wlan0mon

**Comment by strasharo** [comment]
The issue is here:
https://github.com/deltaxflux/flux/blob/master/flux#L614

Current airmon-ng produces output like this:
root@kalif:~# airmon-ng 

PHY	Interface	Driver		Chipset

phy0	alfa1		rtl8187		Realtek Semiconductor Corp. RTL8187
phy1	alfa2		ath9k_htc	Atheros Communications, Inc. AR9271 802.11n

root@kalif:~# 

Where lines containing adapters don't contain a dash (-) as your script expects.

Your script is relying on output like this:
root@kalif:~# ./airmon 


Interface	Chipset		Driver

alfa1		Realtek RTL8187L	rtl8187 - [phy0]
alfa2		Atheros AR9271	ath9k - [phy1]

root@kalif:~# 

Where you have a dash on every line with adapter. 
Such output is provided by the following script:
https://github.com/kernel-64/linset/blob/81e637542b2cd62a6ea6c307183b7488bf8fd277/airmon

There are two options to fix this issue. You can either:
1) Ship a separate airmon script with flux and execute it instead of the OS built-in airmon-ng.
2) Modify the parsing logic of your script to work with the current versions of airmon-ng.

Let me know if you need any assistance with that and please, reopen this issue as it's currently preventing users from using the script.

Thank you.

**Comment by deltaxflux** [comment]
**Bug is fixed**

I fixed the Bug already look at the kali folder, (there is the patch). The patch include some fixes with Aircrack-ng (Aircrack-ng 1.2 RC 4).  However mon0 changed to wlan0. Futhermore this was the problem for flux, so i created fluxion includet a airmon file. So it should work on Kali 2 and Kali 2016. 
If you want more details please ask me.

**Comment by fabianlim1989** [comment]
@deltaxflux I am still getting the error of `There are no wireless card... quit`

I am running `kali 2.0, 4.6.0-kalil-amd64`
I have ALFA AWUS036AC installed. let me know what to do. Thanks.

```
root@kali:~/Downloads/fluxion-master# iwconfig
lo        no wireless extensions.

wlan0     unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

eth0      no wireless extensions.
```

**Comment by Vigilence** [comment]
@fabianlim1989 Can you confirm that this wireless card supports monitor mode and AP mode?  I was interested in this card some time back, but there weren't any compatible drivers for it on any pen-testing OS.  Has this changed?

**Comment by fabianlim1989** [comment]
@Vigilence you might be right... https://forum.aircrack-ng.org/index.php?topic=1186.0
I had tried to install a number of drivers to my kali but to no avail. I have the Wifi Pineapple too though. I can try using that for now.

**Comment by Vigilence** [comment]
@fabianlim1989 sorry to hear that.

**Comment by fabianlim1989** [comment]
@Vigilence so i managed to get AWUS036AC into monitor mode after tweaks. But the fluxsion isn't working. is there something i can check to get it working?

![monitormode](https://cloud.githubusercontent.com/assets/4744132/19219006/b02988ba-8e3a-11e6-8acc-d8ce4355b6f4.jpg)

**Comment by mrxrom** [comment]
Hello i'm new to linux and having the exact same problem : 

After running fluxion ,and choosing the language , there is like a screen change in the top bar of kali and the wifi have disapear from the right menu

in fluxion i choose "All channels" and it writes :
i Error : your wireless card isn't supported 
Do you want to exit ?  

i'm running kali 2016 in VirtualBox with the correct wifi adapter (Alfa AWUSO36H)

Someone have an idea to make it work ?

i have read this post but my level in linux (and in english ;) ) isn't good enough to do one of these 2 solutions : 

    1 Ship a separate airmon script with flux and execute it instead of the OS built-in airmon-ng.
    2 Modify the parsing logic of your script to work with the current versions of airmon-ng.

Could someone help me resolving that please ?

**Comment by teabag178** [comment]
hey guys ...

can anyone help me when i run airmon-ng it does detect my wireless cards i can even put it into monitor mode but when i run fluxion or linset it tells me no wireless cards detected..

please help!!
